name: Test CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '12', '14', '16' ]
    name: Node ${{ matrix.node }} sample
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
# auth service       
      - name : install auth dependecy
        run: npm install
        working-directory: auth
      - name : run auth test
        run: npm run test
        working-directory: auth
# ticket service        
      - name : install tickets dependecy
        run: npm install
        working-directory: tickets
      - name : run tickets test
        run: npm run test
        working-directory: tickets
